apiVersion: apps/v1
kind: Deployment
metadata:
  name: s10-api-gateway
  namespace: stablebridge
  labels:
    app: s10-api-gateway
    service: api-gateway-iam
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: s10-api-gateway
  template:
    metadata:
      labels:
        app: s10-api-gateway
        service: api-gateway-iam
    spec:
      containers:
        - name: s10-api-gateway
          image: stablebridge/api-gateway-iam:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: s10-config
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          readinessProbe:
            httpGet:
              path: /gateway/actuator/health/readiness
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /gateway/actuator/health/liveness
              port: 8080
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 5
