apiVersion: v1
kind: Service
metadata:
  name: s10-api-gateway
  namespace: stablebridge
  labels:
    app: s10-api-gateway
spec:
  type: ClusterIP
  selector:
    app: s10-api-gateway
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
