apiVersion: v1
kind: Service
metadata:
  name: s13-merchant-iam
  namespace: stablebridge
  labels:
    app: s13-merchant-iam
spec:
  type: ClusterIP
  selector:
    app: s13-merchant-iam
  ports:
    - port: 8083
      targetPort: 8083
      protocol: TCP
      name: http
