app:
  security:
    enabled: false
  fallback-adapters:
    enabled: true

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/s11_merchant_onboarding
    username: sp_user
    password: sp_pass

  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092

  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: false

logging:
  level:
    com.stablecoin.payments: DEBUG
    org.springframework.cloud.stream: DEBUG
