apiVersion: v1
kind: Service
metadata:
  name: merchant-portal
  namespace: stablebridge
  labels:
    app: merchant-portal
spec:
  type: ClusterIP
  selector:
    app: merchant-portal
  ports:
    - port: 3000
      targetPort: 80
      protocol: TCP
      name: http
