apiVersion: v1
kind: ConfigMap
metadata:
  name: s11-config
  namespace: stablebridge
  labels:
    app: s11-merchant-onboarding
data:
  SPRING_PROFILES_ACTIVE: "local,sandbox"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://host.docker.internal:5432/s11_merchant_onboarding"
  SPRING_DATASOURCE_USERNAME: "dev"
  SPRING_DATASOURCE_PASSWORD: "dev"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "host.docker.internal:9092"
  SPRING_DATA_REDIS_HOST: "host.docker.internal"
  SPRING_DATA_REDIS_PORT: "6379"
  TEMPORAL_HOST: "host.docker.internal"
  TEMPORAL_PORT: "7233"
  ONFIDO_BASE_URL: "http://host.docker.internal:4444/v3.6"
  ONFIDO_API_TOKEN: "sandbox-token"
  ONFIDO_WEBHOOK_SECRET: "sandbox-webhook-secret"
  COMPANIES_HOUSE_BASE_URL: "http://host.docker.internal:4444"
  COMPANIES_HOUSE_API_KEY: "sandbox-key"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://host.docker.internal:4318/v1/traces"
