apiVersion: apps/v1
kind: Deployment
metadata:
  name: s11-merchant-onboarding
  namespace: stablebridge
  labels:
    app: s11-merchant-onboarding
    service: merchant-onboarding
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: s11-merchant-onboarding
  template:
    metadata:
      labels:
        app: s11-merchant-onboarding
        service: merchant-onboarding
    spec:
      containers:
        - name: s11-merchant-onboarding
          image: stablebridge/merchant-onboarding:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8081
              protocol: TCP
          envFrom:
            - configMapRef:
                name: s11-config
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          readinessProbe:
            httpGet:
              path: /onboarding/actuator/health/readiness
              port: 8081
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /onboarding/actuator/health/liveness
              port: 8081
            initialDelaySeconds: 60
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 5
