apiVersion: v1
kind: Service
metadata:
  name: s11-merchant-onboarding
  namespace: stablebridge
  labels:
    app: s11-merchant-onboarding
spec:
  type: ClusterIP
  selector:
    app: s11-merchant-onboarding
  ports:
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: http
